/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Core background scale
        'bg-900': '#FFFFFF',
        'bg-800': '#F4F8FD',
        'bg-700': '#FFFFFF',
        'bg-600': '#E2E8F0',
        'bg-500': '#94A3B8',
        'bg-400': '#64748B',

        // Primary accent - Blue
        'ice-blue': '#3B82F6',
        'ice-blue-dark': '#2563EB',
        'ice-blue-glow': 'rgba(59,130,246,0.15)',
        'ice-blue-subtle': 'rgba(59,130,246,0.04)',

        // Text
        'text-primary': '#081120',
        'text-secondary': '#475569',
        'text-muted': 'rgba(8,17,32,0.6)',
        'text-dim': 'rgba(8,17,32,0.35)',

        // Borders
        'border-subtle': 'rgba(20,50,100,0.08)',
        'border-mid': 'rgba(20,50,100,0.12)',
        'border-strong': 'rgba(20,50,100,0.2)',

        // Legacy Stitch tokens mapped to the new aesthetic
        "primary": "#3B82F6",
        "primary-container": "#2563EB",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#081120",
        "secondary": "#475569",
        "on-secondary": "#FFFFFF",
        "surface": "#FFFFFF",
        "surface-container": "#F4F8FD",
        "surface-container-low": "#F8FAFC",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-high": "#E2E8F0",
        "surface-container-highest": "#CBD5E1",
        "surface-variant": "#F4F8FD",
        "on-surface": "#081120",
        "on-surface-variant": "#475569",
        "background": "#FFFFFF",
        "on-background": "#081120",
        "outline": "#94A3B8",
        "outline-variant": "#CBD5E1",
        "error": "#EF4444",
        "inverse-surface": "#081120",
        "inverse-on-surface": "#FFFFFF",
      },
      spacing: {
        'section': '120px',
        'section-sm': '80px',
        'gutter': '24px',
        'margin-desktop': '80px',
        'margin-mobile': '20px',
        'base': '8px',
        'sm': '16px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'xxl': '120px',
      },
      borderRadius: {
        'DEFAULT': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        'full': '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-lg': ['Inter'],
        'headline-xl': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-sm': ['Inter'],
        'label-bold': ['Inter'],
      },
      fontSize: {
        'display': ['96px', { lineHeight: '1', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-md': ['72px', { lineHeight: '1.05', letterSpacing: '-0.025em', fontWeight: '800' }],
        'display-sm': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-sm': ['22px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-xl': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.1em', fontWeight: '500' }],
        'label-bold': ['14px', { lineHeight: '1.4', fontWeight: '700' }],
      },
      animation: {
        'fade-up': 'fadeUp 0.7s cubic-bezier(0.16,1,0.3,1) forwards',
        'fade-in': 'fadeIn 0.5s ease forwards',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'spin-slow': 'spin 20s linear infinite',
        'marquee': 'marquee 30s linear infinite',
        'marquee-reverse': 'marqueeReverse 30s linear infinite',
        'float': 'float 4s ease-in-out infinite',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 15px rgba(96,165,250,0.15)' },
          '50%': { boxShadow: '0 0 25px rgba(96,165,250,0.3)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        marqueeReverse: {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
      },
    },
  },
  plugins: [],
}
